language: android
jdk: oraclejdk8
sudo: false

env:
  matrix:
    - ANDROID_TARGET=android-23 ANDROID_ABI=armeabi-v7a
  global:   #Optional
    - ADB_INSTALL_TIMEOUT=10    #Time out to 10 mins

android:
    update_sdk: true  #Check for the updates each time you run the build.
    components:
        - platform-tools
        - tools
        - build-tools-25.0.0    #Build tool version
        - android-25            #targate api version

        # Additional components
        - extra-google-google_play_services
        - extra-google-m2repository
        - extra-android-m2repository

        #system images for emulator
        - sys-img-armeabi-v7a-android-23
before_script:
    - chmod +x gradlew      #Grant permissions
    - android list targets
    - echo no | android create avd --force --name test --target $ANDROID_TARGET --abi $ANDROID_ABI    #Create AVD for given api
    - emulator -avd test -no-skin -no-audio -no-window &    #Start emulator

script:
    - echo "Travis branch is $TRAVIS_BRANCH"    #Print out which branch it is.
    - echo "Travis branch is in pull request $TRAVIS_PULL+REQUEST"    #Print out pull request number.
    - android-wait-for-emulator             #Run wait for the emulator script.
    - adb devices                           #Display list of devices
    - adb shell input keyevent 82 &
    - ./gradlew connectedAndroidTest -PdisablePreDex --stacktrace

before_install:
    - pip install --user codecov    #Install codecov

after_success:
    - codecov                       #Run codecov
